#!/bin/sh


##
## /usr/lib/live/config/5010-user-change-password
##


##
## ## Load Lib
##

. /lib/live/config.sh


##
## live-config(7) - System Configuration Components
##

##
## > Refer: [/usr/lib/live/config/0030-user-setup](https://salsa.debian.org/live-team/live-config/-/blob/master/components/0030-user-setup?ref_type=heads)
##


#set -e


Cmdline ()
{
	# Reading kernel command line
	for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.user-default-groups=*|user-default-groups=*)
				LIVE_USER_DEFAULT_GROUPS="${_PARAMETER#*user-default-groups=}"
				;;

			live-config.user-fullname=*|user-fullname=*)
				LIVE_USER_FULLNAME="${_PARAMETER#*user-fullname=}"
				;;

			live-config.username=*|username=*)
				LIVE_USERNAME="${_PARAMETER#*username=}"
				;;
		esac
	done
}

Init () {

	##
	## ## Checking if package is installed
	##

	if ! pkg_is_installed "passwd" || \
		component_was_executed "passwd"
	then
		exit 0
	fi

	echo -n " passwd"
}

Config () {

	##
	## ## change user password
	##
	## > echo 'username:password' | chpasswd
	##

	local user_name="${LIVE_USERNAME}"
	local user_pass="lika"

	echo "${user_name}:${user_pass}" | chpasswd
	#echo 'lika:lika' | chpasswd


	##
	## ## remove user password
	##

	#passwd -d lika


	##
	## ## Creating state file
	##

	touch /var/lib/live/config/user-change-password

}


Cmdline
Init
Config
